spring.application.name=demo

spintg.datasource.url=jdbc:sqlite:estoque.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jps.database-plataform=org.hibernate.commutiny.dialects.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true